<?php
/**
 * Imports AI-generated Moodle XML into a question category and creates a quiz activity.
 *
 * @package    local_umat_ai
 * @copyright  2026 UMaT
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_umat_ai\quiz;

defined('MOODLE_INTERNAL') || die();

require_once($CFG->dirroot . '/question/editlib.php');
require_once($CFG->dirroot . '/mod/quiz/locallib.php');
require_once($CFG->dirroot . '/lib/questionlib.php');
require_once($CFG->dirroot . '/question/format/xml/format.php');

class importer {

    /**
     * Import the XML content into a question category, then create a quiz activity.
     *
     * @param int    $jobid         The quizgen_jobs row id.
     * @param string $xml           The Moodle XML string to import.
     * @param int    $courseid      Target course.
     * @param string $categoryname  Name for the question category.
     * @param int    $userid        The lecturer who requested it (for quiz owner).
     * @return \stdClass With fields: category_id, question_ids[], quiz_id, quiz_cmid.
     */
    public static function import_questions_and_create_quiz(
        int $jobid,
        string $xml,
        int $courseid,
        string $categoryname,
        int $userid
    ): \stdClass {
        global $DB;

        $result = (object)[
            'category_id'  => 0,
            'question_ids' => [],
            'quiz_id'      => 0,
            'quiz_cmid'    => 0,
        ];

        // ── Step 1: Find or create the question category ──
        $context = \context_course::instance($courseid);
        $cat = $DB->get_record('question_categories', [
            'name'      => $categoryname,
            'contextid' => $context->id,
        ]);
        if (!$cat) {
            $cat = (object)[
                'name'        => $categoryname,
                'contextid'   => $context->id,
                'info'        => 'Questions generated by AI (job: ' . $jobid . ')',
                'infoformat'  => FORMAT_HTML,
                'stamp'       => make_unique_id_code(),
                'parent'      => 0,
                'sortorder'   => 999,
            ];
            $cat->id = $DB->insert_record('question_categories', $cat);
        }
        $result->category_id = (int)$cat->id;

        // ── Step 2: Import XML into the category ──
        $qformat = new \qformat_xml();
        $qformat->setCategory($cat);
        $qformat->setContexts([$context]);
        $qformat->setCourse($courseid);
        $qformat->setFilenameFromString('quizgen_job_' . $jobid);

        $qformat->setImportdata($xml);

        if (!$qformat->importpreprocess()) {
            throw new \moodle_exception('quizgen_import_preprocess_failed', 'local_umat_ai');
        }

        if (!$qformat->importprocess(null)) {
            $errors = $qformat->get_errors();
            throw new \moodle_exception('quizgen_import_process_failed', 'local_umat_ai', '', null, implode("\n", $errors ?? []));
        }

        $qformat->importpostprocess();

        $result->question_ids = $qformat->get_imported_question_ids();

        // ── Step 3: Create a quiz activity ──
        $quiz = (object)[
            'course'           => $courseid,
            'name'             => $categoryname,
            'intro'            => get_string('quizgen_auto_intro', 'local_umat_ai'),
            'introformat'      => FORMAT_HTML,
            'timeopen'         => 0,
            'timeclose'        => 0,
            'preferredbehaviour' => 'deferredfeedback',
            'attempts'         => -1,
            'grademethod'      => GRADEHIGHEST,
            'decimalpoints'    => 2,
            'questionsperpage' => 0,
            'shufflequestions' => 0,
            'shuffleanswers'   => 1,
            'sumgrades'        => count($result->question_ids),
            'grade'            => 100,
            'timecreated'      => time(),
            'timemodified'     => time(),
        ];

        $quiz->id = $DB->insert_record('quiz', $quiz);

        $cm = new \stdClass();
        $cm->course     = $courseid;
        $cm->module     = $DB->get_field('modules', 'id', ['name' => 'quiz']);
        $cm->instance   = $quiz->id;
        $cm->section    = 0;
        $cm->visible    = 0;
        $cm->visibleold = 0;
        $cm->added      = time();
        $cm->id = $DB->insert_record('course_modules', $cm);

        $result->quiz_cmid = (int)$cm->id;
        $result->quiz_id   = (int)$quiz->id;

        foreach ($result->question_ids as $qid) {
            $slot = (object)[
                'quiz'       => $quiz->id,
                'slot'       => 0,
                'questionid' => $qid,
                'maxmark'    => 1,
            ];
            $slot->id = $DB->insert_record('quiz_slots', $slot);
        }

        quiz_update_sumgrades($quiz);
        quiz_update_grades($quiz);

        rebuild_course_cache($courseid, true);

        return $result;
    }

    /**
     * Append new questions from AI-generated XML into an existing quiz.
     *
     * Uses the same question category as the existing quiz's first question.
     *
     * @param int    $jobid           The quizgen_jobs row id for this new batch.
     * @param string $xml             The Moodle XML string to import.
     * @param int    $existingQuizId  ID of the existing quiz activity.
     * @param string $categoryname    Fallback category name if no questions exist yet.
     * @return \stdClass With fields: category_id, question_ids[], quiz_id, quiz_cmid.
     */
    public static function append_to_existing_quiz(
        int $jobid,
        string $xml,
        int $existingQuizId,
        string $categoryname
    ): \stdClass {
        global $DB;

        $result = (object)[
            'category_id'  => 0,
            'question_ids' => [],
            'quiz_id'      => $existingQuizId,
            'quiz_cmid'    => 0,
        ];

        $quiz = $DB->get_record('quiz', ['id' => $existingQuizId], '*', MUST_EXIST);
        $courseid = (int)$quiz->course;
        $context = \context_course::instance($courseid);

        // Find the category used by the first question in the existing quiz.
        $existingSlot = $DB->get_record_sql(
            'SELECT qs.questionid FROM {quiz_slots} qs WHERE qs.quiz = ? ORDER BY qs.slot ASC LIMIT 1',
            [$existingQuizId]
        );

        $cat = null;
        if ($existingSlot) {
            $catId = $DB->get_field('question', 'category', ['id' => $existingSlot->questionid]);
            if ($catId) {
                $cat = $DB->get_record('question_categories', ['id' => $catId]);
            }
        }

        if (!$cat) {
            $cat = $DB->get_record('question_categories', [
                'name'      => $categoryname,
                'contextid' => $context->id,
            ]);
            if (!$cat) {
                $cat = (object)[
                    'name'        => $categoryname,
                    'contextid'   => $context->id,
                    'info'        => 'Questions generated by AI (job: ' . $jobid . ')',
                    'infoformat'  => FORMAT_HTML,
                    'stamp'       => make_unique_id_code(),
                    'parent'      => 0,
                    'sortorder'   => 999,
                ];
                $cat->id = $DB->insert_record('question_categories', $cat);
            }
        }
        $result->category_id = (int)$cat->id;

        // Import XML into the found/created category.
        $qformat = new \qformat_xml();
        $qformat->setCategory($cat);
        $qformat->setContexts([$context]);
        $qformat->setCourse($courseid);
        $qformat->setFilenameFromString('quizgen_job_' . $jobid . '_append');
        $qformat->setImportdata($xml);

        if (!$qformat->importpreprocess()) {
            throw new \moodle_exception('quizgen_import_preprocess_failed', 'local_umat_ai');
        }

        if (!$qformat->importprocess(null)) {
            $errors = $qformat->get_errors();
            throw new \moodle_exception('quizgen_import_process_failed', 'local_umat_ai', '', null, implode("\n", $errors ?? []));
        }

        $qformat->importpostprocess();

        $result->question_ids = $qformat->get_imported_question_ids();

        // Figure out next slot number.
        $maxSlot = $DB->get_field_sql(
            'SELECT COALESCE(MAX(qs.slot), 0) FROM {quiz_slots} qs WHERE qs.quiz = ?',
            [$existingQuizId]
        );

        foreach ($result->question_ids as $qid) {
            $maxSlot++;
            $slot = (object)[
                'quiz'       => $existingQuizId,
                'slot'       => $maxSlot,
                'questionid' => $qid,
                'maxmark'    => 1,
            ];
            $slot->id = $DB->insert_record('quiz_slots', $slot);
        }

        quiz_update_sumgrades($quiz);
        quiz_update_grades($quiz);

        $cm = $DB->get_record('course_modules', ['instance' => $existingQuizId, 'module' => $DB->get_field('modules', 'id', ['name' => 'quiz'])]);
        $result->quiz_cmid = $cm ? (int)$cm->id : 0;

        rebuild_course_cache($courseid, true);

        return $result;
    }
}
