<#
.SYNOPSIS
  Start tunnels to expose local Moodle (+ AI service) to the internet via ngrok.
.DESCRIPTION
  1. Starts a tunnel for Moodle (port 80) and AI service (port 8000).
  2. Captures the tunnel URLs from ngrok API.
  3. Updates Moodle's wwwroot + sslproxy via tunnel_config.php.
  4. Updates the AI service endpoint URL in Moodle's plugin config.
.NOTES
  Requires ngrok (already installed + authenticated on this machine).
  Run from PowerShell as Administrator.
  Press Ctrl+C to stop (or run scripts/stop_tunnels.ps1).
#>

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path $PSScriptRoot -Parent
$TunnelConfig = Join-Path $ProjectRoot "moodle\tunnel_config.php"

# --- 1. Verify ngrok ---
$ngrokPath = (Get-Command ngrok -ErrorAction Stop).Source
Write-Output "Using ngrok: $ngrokPath"

# --- 2. Kill any existing tunnels ---
Get-Process ngrok -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 2

# --- 3. Start Moodle tunnel ---
Write-Output "Starting ngrok tunnel for Moodle (port 80)..."
$moodleJob = Start-Job -ScriptBlock {
    param($root)
    $log = Join-Path $root "moodle_tunnel_url.txt"
    ngrok http 80 --log=stdout 2>&1 | ForEach-Object {
        if ($_ -match 'url=https?://\S+') {
            $matches[0] -replace 'url=', '' | Out-File -Encoding UTF8 -FilePath $log
        }
        Write-Output $_
    }
} -ArgumentList $ProjectRoot

# --- 4. Start AI service tunnel ---
Write-Output "Starting ngrok tunnel for AI Service (port 8000)..."
$aiJob = Start-Job -ScriptBlock {
    param($root)
    $log = Join-Path $root "ai_tunnel_url.txt"
    ngrok http 8000 --log=stdout 2>&1 | ForEach-Object {
        if ($_ -match 'url=https?://\S+') {
            $matches[0] -replace 'url=', '' | Out-File -Encoding UTF8 -FilePath $log
        }
        Write-Output $_
    }
} -ArgumentList $ProjectRoot

# --- 5. Wait for URLs ---
Write-Output "Waiting for tunnel URLs (this takes ~10-15 seconds)..."
Start-Sleep -Seconds 15

$moodleLog = Join-Path $ProjectRoot "moodle_tunnel_url.txt"
$aiLog = Join-Path $ProjectRoot "ai_tunnel_url.txt"

# Retry loop
$retries = 0
$moodleUrl = ""
$aiUrl = ""
while ($retries -lt 6) {
    if (Test-Path $moodleLog) { $moodleUrl = (Get-Content $moodleLog -Raw).Trim() }
    if (Test-Path $aiLog) { $aiUrl = (Get-Content $aiLog -Raw).Trim() }
    if ($moodleUrl -ne "" -and $aiUrl -ne "") { break }
    Start-Sleep -Seconds 10
    $retries++
}

# Fallback: fetch from ngrok API
if ($moodleUrl -eq "" -or $aiUrl -eq "") {
    Write-Output "Trying ngrok API (localhost:4040)..."
    Start-Sleep -Seconds 5
    try {
        $api = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -ErrorAction Stop
        $tunnels = $api.tunnels
        foreach ($t in $tunnels) {
            $url = $t.public_url
            $port = $t.config.addr -replace '.*:(\d+).*', '$1'
            if ($port -eq "80") { $moodleUrl = $url }
            if ($port -eq "8000") { $aiUrl = $url }
        }
    } catch {
        Write-Output "ngrok API not available yet."
    }
}

if ($moodleUrl -eq "") {
    Write-Output "ERROR: Could not get Moodle tunnel URL."
    Write-Output "Check ngrok status at http://localhost:4040"
    Get-Process ngrok -ErrorAction SilentlyContinue | Format-Table Id, ProcessName
    exit 1
}

Write-Output "Moodle URL:       $moodleUrl"
Write-Output "AI Service URL:   $($aiUrl -replace '/$','')"

# --- 6. Write tunnel_config.php ---
$tunnelPhp = @"
<?php
// Auto-generated by scripts/start_tunnels.ps1
// Created: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
`$CFG->wwwroot   = '$moodleUrl';
`$CFG->sslproxy  = true;
"@
$tunnelPhp | Out-File -Encoding UTF8 -FilePath $TunnelConfig

Write-Output "Moodle wwwroot updated to: $moodleUrl"

# --- 7. Update AI service URL in Moodle plugin config ---
Write-Output "Updating AI service endpoint in Moodle plugin settings..."
$dbHost = "127.0.0.1"
$dbPort = 5432
$dbName = "moodle"
$dbUser = "postgres"
$dbPass = "seidu"
$aiApiUrl = "$($aiUrl -replace '/$','')/api/v1"

try {
    $env:PGPASSWORD = $dbPass
    & psql -h $dbHost -p $dbPort -U $dbUser -d $dbName -c @"
        UPDATE mdl_config_plugins SET value = '$aiApiUrl'
        WHERE plugin = 'local_umat_ai' AND name = 'service_url'
        AND value != '$aiApiUrl';
"@ 2>&1 | Out-Null
    Write-Output "AI service URL updated to: $aiApiUrl"
} catch {
    Write-Output "WARNING: Could not update DB. Do it manually:"
    Write-Output "  Site Admin -> Plugins -> Local Plugins -> UMaT AI"
    Write-Output "  Set 'Service URL' to: $aiApiUrl"
}

Write-Output ""
Write-Output "=========================================="
Write-Output "  TUNNELS ACTIVE"
Write-Output "  Moodle:       $moodleUrl"
Write-Output "  AI Service:   $(($aiUrl -replace '/$','').PadRight(50))"
Write-Output ""
Write-Output "  Send the Moodle URL to your testers!"
Write-Output "  To stop: Ctrl+C or scripts\stop_tunnels.ps1"
Write-Output "=========================================="

# Keep running until Ctrl+C
while ($true) {
    Start-Sleep -Seconds 5
    if (-not (Get-Process ngrok -ErrorAction SilentlyContinue)) {
        Write-Output "ngrok process died. Check http://localhost:4040 for status."
        break
    }
}
